package io.github.adriandleon.kenvy

internal fun buildLocalPropertiesExample(
    contract: ParsedKenvyContract,
    platform: String?,
    variant: String?
): String {
    val resolved = KenvyResolver.resolve(
        contract = contract,
        platform = platform,
        variant = variant,
        localProperties = emptyMap()
    ) { null }

    return buildString {
        appendLine("# local.properties.example — auto-generated by Kenvy. Copy to local.properties and fill in your values.")
        appendLine("# Do not commit local.properties to version control.")
        appendLine()

        for (rv in resolved) {
            val prop = rv.property
            val escapedKey = KenvyPropertiesFormat.escapePropertyKey(prop.name)
            append("# ${prop.name} (${prop.type.name.lowercase().replaceFirstChar { it.uppercase() }})")
            appendLine()

            if (prop.description != null) {
                appendCommentLines(prop.description)
            }

            if (prop.helpUrl != null) {
                appendCommentLines(prop.helpUrl, prefix = "Setup: ")
            }

            val effectiveSource = rv.source
            val effectiveValue = rv.resolvedValue
            if (effectiveSource.isSharedContractSource() && effectiveValue != null) {
                val sourceLabel = effectiveSource.name.lowercase()
                appendCommentLines(rv.displayValue(), prefix = "Effective shared value from $sourceLabel: ")
            }

            if (prop.isPlaceholder) {
                appendLine("$escapedKey=")
            } else {
                appendLine("# $escapedKey=")
            }

            appendLine()
        }
    }.trimEnd() + "\n"
}

private fun ResolutionSource.isSharedContractSource(): Boolean =
    this == ResolutionSource.COMMON_OVERRIDE ||
        this == ResolutionSource.PLATFORM_OVERRIDE ||
        this == ResolutionSource.VARIANT_OVERRIDE

private fun StringBuilder.appendCommentLines(value: String, prefix: String = "") {
    val lines = value.replace("\r\n", "\n").replace('\r', '\n').split('\n')
    lines.forEachIndexed { index, line ->
        val linePrefix = if (index == 0) prefix else ""
        appendLine("# $linePrefix$line")
    }
}
